language: python
sudo: true

python:
  - 2.7

services:
  - docker

before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install -r requirements.txt

  # Mock credentials
  - export AWS_ACCESS_KEY_ID=1
  - export AWS_SECRET_ACCESS_KEY=1

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - py.test --cov=dec2 dec2/tests --cov-report term-missing --cov-report html -s -vv
